### PR TITLE
Add a color theme based on the MPIDR colors

### PR DESCRIPTION
**Pull request by ohexel**
Add a beamer color theme based on the colors defined in the MPIDR presentation guide. Explain how to use the color theme.

### CODE REVIEW

**Comment by tomthe** [comment]
Nice!

And all this explanation in the readme!

Would it be helpful for most people, if we include the stork color theme by default? Why not?

Also, after reading the readme: Why do I need this at all?

**Comment by tomthe** [comment]
Can we add something directly after the headline "# The `stork` color theme"?
`The stork color theme is a Latex color theme based on the corporate design of the MPIDR. Its colors are taken from the Powerpoint template (2021). When you include this theme, you can use....

**Comment by ohexel** [comment]
Why: having a separate color theme allows the user to pick whatever overall theme they prefer (i.e. the general layout of the slides).

Include by default: I don't make any promises regarding aesthetics but it shouldn't break anything (defining colors for elements is cumulative).

**Comment by tomthe** [comment]
Thank you very much!

**Pull request merged**
